### ISSUE TITLE
Issue Mailjet 

### ISSUE THREAD

**Issue by shemzo** [mailjet/MailjetSwiftMailer#11]
hello , i have an issue i get an error message when i load the page that sends my message : Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "swiftmailer.mailer.transport.mailjet"
thanks

**Comment by Nightbr** [comment]
Hi, can you describe your configuration and environment (your framework and version).
Add to that, can you give us the version of SwiftMailer you're using.

Thanks!

**Comment by shemzo** [comment]
hi , i m using  symfony 3.3 and using the version 2.3.10 of Swiftmailer
thank you for your response

**Comment by Nightbr** [comment]
Try to use the Symfony bundle to integrate mailjet with Symfony https://github.com/mailjet/mailjetBundle

it includes the transport mailjet already configured!

**Comment by shemzo** [comment]
okey thank you

**Comment by Nightbr** [comment]
Let me know if it works!

**Comment by shemzo** [comment]
it did solve the problem thank you
