### ISSUE TITLE
Sandbox Mode

### ISSUE THREAD

**Issue by qdequippe** [mailjet/MailjetSwiftMailer#19]
Hi,

Is there a way to use [Sandbox Mode](https://dev.mailjet.com/guides/?shell#sandbox-mode)? I tried by setting this in the headers

```php
$headers = $message->getHeaders();
$headers->addTextHeader('X-MJ-SandboxMode', true);
// or
$headers->addTextHeader('SandboxMode', true);
```
but without success, the email is still sent.

Regards

**Comment by qdequippe** [comment]
Any help?

**Comment by bertoost** [comment]
Would be nice to have this included in the package.
Hope @bench @eboisgon @ngarnier or @Nightbr are able to be a little more active on this
